
BASES = ['T', 'C', 'A', 'G']

chr_name_dict_all = {
    '1': 'YHet',
    '2': 'dmel_mitochondrion_genome',
    '3': '2L',
    '4': 'X',
    '5': '3L',
    '6': '4',
    '7': '2R',
    '8': '3R',
    '9': 'Uextra',
    '10': '2RHet',
    '11': '2LHet',
    '12': '3LHet',
    '13': '3RHet',
    '14': 'U',
    '15': 'XHet'
}

chr_name_dict_auto = {
    '3': '2L',
    '5': '3L',
    '6': '4',
    '7': '2R',
    '8': '3R',
    '10': '2RHet',
    '11': '2LHet',
    '12': '3LHet',
    '13': '3RHet',
}

TISSUE_TYPES_a = {
    't1': 'Ad hindgut',
    't2': 'Ad midgut',
    't3': 'Ad male ac gl',
    't4': 'Ad brain',
    't5': 'Ad crop',
    't6': 'Lv wd fat body * cut *',
    't7': 'Ad head * cut *',
    't8': 'Lv wd Tubules * cut *',
    't9': 'Ad ovary',
    't10': 'Ad testis',
    't11': 'Ad wh fly',
    't12': 'Ad Salivary gl',
    't13': 'Ad carcass',
    't14': 'Ad TA ganglion * cut *',
    't15': 'Lv fd hindgut',
    't16': 'Lv fd midgut',
    't17': 'Lv fd Salivary gl',
    't18': 'Ad M spermatheca   * cut *',
    't19': 'Ad V spermatheca   * cut *',
    't20': 'Lv fd tubule',
    't21': 'Lv fd fat body',
    't22': 'Lv fd carcass',
    't23': 'Lv fd CNS',
    't24': 'Lv fd trachea',
    't25': 'S2 cells gr  * cut *',
    't26': 'Ad fat body',
    't27': 'Ad eye',
    't28': 'Ad heart',
    't29': 'Ad male Ej Dt',
    't30': 'Lv wh fd',
    't31': 'Ad female',
    't32': 'Ad male',
    't33': 'Sp mitotic',
    't34': 'Sp meiotic',
    't35': 'Sp p-meiotic',
    't36': 'embryo_0_2',
    't37': 'embryo_4_6',
    't38': 'embryo_8-10',
    't39': 'embryo_4_10',
    't40': 'larval_fed',
    't41': 'larval_st'
}

